# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itcast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0citcast.proto\"}\n\x04Work\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x1b\n\x02op\x18\x03 \x01(\x0e\x32\x0f.Work.Operation\"<\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\"\x15\n\x06Result\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x14\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x07Subject\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x05\x44\x65lta\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x12\n\x03Sub\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x15\n\x06Number\x12\x0b\n\x03val\x18\x01 \x01(\x05\"#\n\x06\x41nswer\x12\x0b\n\x03val\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t2\x90\x01\n\x04\x44\x65mo\x12\x1d\n\tCalculate\x12\x05.Work\x1a\x07.Result\"\x00\x12\"\n\x0bGetSubjects\x12\x05.City\x1a\x08.Subject\"\x00\x30\x01\x12\x1e\n\nAccumulate\x12\x06.Delta\x1a\x04.Sub\"\x00(\x01\x12%\n\x0bGuessNumber\x12\x07.Number\x1a\x07.Answer\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itcast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORK._serialized_start=16
  _WORK._serialized_end=141
  _WORK_OPERATION._serialized_start=81
  _WORK_OPERATION._serialized_end=141
  _RESULT._serialized_start=143
  _RESULT._serialized_end=164
  _CITY._serialized_start=166
  _CITY._serialized_end=186
  _SUBJECT._serialized_start=188
  _SUBJECT._serialized_end=211
  _DELTA._serialized_start=213
  _DELTA._serialized_end=233
  _SUB._serialized_start=235
  _SUB._serialized_end=253
  _NUMBER._serialized_start=255
  _NUMBER._serialized_end=276
  _ANSWER._serialized_start=278
  _ANSWER._serialized_end=313
  _DEMO._serialized_start=316
  _DEMO._serialized_end=460
# @@protoc_insertion_point(module_scope)
